# AUTH (αν χρειάζεται)
# Authorization: Bearer {{TOKEN}}

### Create property
POST http://localhost:5001/api/properties
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "landlordId": "{{LANDLORD_ID}}",
  "title": "Apt 401",
  "address": "Pine 12",
  "rent": 650
}

### List properties
GET http://localhost:5001/api/properties
Authorization: Bearer {{TOKEN}}
